"""add cascade delete world sessions documents messages

Revision ID: 3d59ee7363ca
Revises: 2022e607aa02
Create Date: 2026-03-20 12:32:09.522921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d59ee7363ca'
down_revision: Union[str, Sequence[str], None] = '2022e607aa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# alembic/versions/xxxx_cascade_delete.py

def upgrade() -> None:
    # sessions.world_id → ondelete CASCADE
    op.drop_constraint("sessions_world_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_world_id_fkey",
        "sessions", "worlds",
        ["world_id"], ["id"],
        ondelete="CASCADE",
    )

    # messages.session_id → ondelete CASCADE
    op.drop_constraint("messages_session_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_session_id_fkey",
        "messages", "sessions",
        ["session_id"], ["id"],
        ondelete="CASCADE",
    )

    # documents.world_id → ondelete CASCADE
    op.drop_constraint("documents_world_id_fkey", "documents", type_="foreignkey")
    op.create_foreign_key(
        "documents_world_id_fkey",
        "documents", "worlds",
        ["world_id"], ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint("sessions_world_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_world_id_fkey",
        "sessions", "worlds",
        ["world_id"], ["id"],
    )

    op.drop_constraint("messages_session_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_session_id_fkey",
        "messages", "sessions",
        ["session_id"], ["id"],
    )

    op.drop_constraint("documents_world_id_fkey", "documents", type_="foreignkey")
    op.create_foreign_key(
        "documents_world_id_fkey",
        "documents", "worlds",
        ["world_id"], ["id"],
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_world_id_fkey'), 'sessions', 'worlds', ['world_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_session_id_fkey'), 'messages', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_world_id_fkey'), 'documents', 'worlds', ['world_id'], ['id'])
    op.create_table('chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chunks_pkey'))
    )
    op.create_index(op.f('ix_chunks_world_id'), 'chunks', ['world_id'], unique=False)
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('alembic_version_rag',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_rag_pkc'))
    )
    # ### end Alembic commands ###
